require: rubocop-rails

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/*"
    - "Gemfile"
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Rails/InverseOf:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false